### Introduction to NumPy>>>

### Yeni sayfa

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
type(np.array(my_list))

numpy.ndarray

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.zeros ((5,), dtype = int, order='F')

array([0, 0, 0, 0, 0])

In [13]:
np.zeros ((5,3,2), dtype = int, order='C')

array([[[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0],
        [0, 0]]])

In [14]:
np.ones(4,)

array([1., 1., 1., 1.])

In [15]:
np.ones(4, dtype= int)

array([1, 1, 1, 1])

In [16]:
np.ones((3,4)) # iki boyutludur ciktida siranin onunde iki tane koseli parentez oldugunu gorursun

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.ones((2,4))*5 # Elemanlarının hepsi 5 olan 2*4 bir array oluşturmamızı sağlar.

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [18]:
np.full((2,3),8) # Elemanları aynı olan array oluşturmak için full() metodunu da kullanabiliriz.(2,3) dizinin boyutunu belirtirken, matrisin 8’lerden oluşmasını istedik.

array([[8, 8, 8],
       [8, 8, 8]])

In [19]:
np.linspace(0,5,100) # 0 dan baslayip 5 te bitecek sekilde araligi kumulatif olarak 100 e boluyor. 100 nokta sayisi burada tek boyutlu bir dizindir. tek koseli parenez var

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [20]:
np.linspace(0,2,9) # 0 ile 2 arasında bu sayılarda dahil olmak üzere 9 sayı oluşturduk.

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [21]:
np.linspace(1,20,4)

array([ 1.        ,  7.33333333, 13.66666667, 20.        ])

In [22]:
np.eye(5) # 5*5 bir birim matris oluşturmamızı sağlar.

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.7495891 , 0.00213182, 0.27697648, 0.26956941, 0.19172286])

In [24]:
np.random.rand(5,5) # Yani bu, rastgele sayılardan oluşan beşe beşlik bir matris istersem, geçiyorum ve 5 yerine 5 geliyor

array([[0.28898672, 0.37464855, 0.65075899, 0.68364156, 0.4754904 ],
       [0.87351365, 0.47375107, 0.46825194, 0.50855691, 0.07535361],
       [0.15220049, 0.47328773, 0.67838537, 0.73250464, 0.11541951],
       [0.34808649, 0.95283638, 0.68750781, 0.33874624, 0.30076147],
       [0.76105898, 0.54649689, 0.98908429, 0.64472271, 0.78279785]])

In [25]:
np.random.randn(4,4)

array([[ 0.20177326,  1.87881442, -0.77386626,  0.30421942],
       [ 0.39615225, -0.61656563,  0.2126571 ,  0.1054336 ],
       [-0.31889683, -0.27595024, -0.09853966,  0.73822357],
       [-0.45497602,  0.42870608,  1.93659   , -1.88341446]])

In [26]:
np.random.randint(0,50,5) # 0 ve 50 arasında 5 tane rastgele sayı üret

array([47, 18, 46,  4, 36])

In [27]:
np.random.rand(5) # 0 ile 1 arasında 5 random sayı üret.

array([0.2029604 , 0.14968627, 0.51032797, 0.23821453, 0.17019312])

In [28]:
np.random.randint(1,100) # öğreneceğimiz bir dizi Rand int'dir ve bu, düşükten yükseğe rastgele tamsayılar döndürür. Örneğin, 1'den 100'e kadar derseniz, 1 ile 100 arasında rastgele bir tamsayı elde edersiniz ve düşük olan

55

In [29]:
np.random.randint(1,100, 10) # Ve belirli sayıda rastgele tamsayı istiyorsanız, bunları üçüncü bir argüman olarak iletebilirsiniz.

array([16, 55, 61, 60,  7, 64, 83, 26, 26, 34])

In [30]:
arr = np.arange(25) # Array değişken diyeceğim ve bunun saf aralık 25'e eşit olduğunu söyleyeceğim.

In [31]:
arr # Yani AR'nin neye benzediğini kontrol edersem, burada 24'e kadar sıfırdan oluşan tek boyutlu bir dizi.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
ranarr = np.random.randint(0,50,10)

In [33]:
ranarr

array([11, 48, 21, 15, 34, 19,  2,  1, 35, 31])

In [34]:
arr.reshape(5,5)#Bir dizide kullanabileceğiniz en kullanışlı yöntemlerden biri yeniden şekillendirme yöntemidir.

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
ranarr.max()# Tamam hadi içeri girelim ve maksimum veya minimum değerleri bulmak veya değerlerini bulmak için birkaç yararlı yöntem gösterelim.

48

In [36]:
ranarr.min()

1

In [37]:
ranarr.argmax() # Yani, bu Max'in 49'da bulunan indeks değerinin gerçekten ne olduğunu bilmek istersem Ranh'ın Argive olduğunu söyleyebilirim.

1

In [38]:
ranarr.argmin() # Yani 8 endeks konumudur, minimum değer ve minimum değer 0 sifirdir.

7

In [39]:
arr.shape # Burada 25 Khama elde ettiğime dikkat edin ve bu, dizi'nin sadece tek boyutlu bir vektör olduğunu gösteriyor

(25,)

In [40]:
arr = arr.reshape(5,5) # Yani beşe beş olarak yeniden şekillendirildi diyeceğim ve bunu R'ye eşit ayarlayacağım ..

In [41]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
arr.dtype # Hangi veri türüne sahip olduğunuzu merak ediyorsanız, sadece arr diyebilir ve bir öznitelik olarak yazabilirsiniz.

dtype('int32')

In [43]:
from numpy.random import randint # Pekala ve son bir ipucu size göstermek istiyorum eğer rasgele NPE yazmak zorunda kalmak istemiyorsanız

# Rand yapabileceğiniz şey, PI'dan rastgele ithalatı ve daha sonra yöntem veya işlevi ne olursa olsun söyleyebilmenizdir.

In [44]:
randint(2,10)

9

In [45]:
a = np.arange(15).reshape(3,5) #arange()metodu ile 0’dan 15’e kadar bir #dizi yaratıyoruz.reshape() metodu ile 3*5’lik bir matris şekillendirmiş #oluyoruz.

In [46]:
# a.reshape(3,5) # reshape() metodu ile 3*5’lik bir matris şekillendirmiş #oluyoruz. #oluşturduğumuz a array’ini görelim

In [47]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [48]:
a.shape # Dizi boyutunu verir. a X b matrisi (a,b) olarak döner. uc satir 5 sutun demektir

(3, 5)

In [49]:
a.ndim # a’nın rankıni yani boyut sayisini verir burada a matrisi iki boyutlu bir matristir

2

In [50]:
a.size # Dizideki eleman sayısını verir. Yani a*b işleminin sonucudur.

15

In [51]:
a.dtype #  Dizideki eleman türünü döndürür.

dtype('int32')

In [52]:
type(a)  #oluşturduğumuz a array’inin türünü görmek istersek

numpy.ndarray

In [53]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [54]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [55]:
np.linspace(0,40,5)

array([ 0., 10., 20., 30., 40.])

NumPy Indexing and Selection

In [56]:
import numpy as np

In [57]:
arr = np.arange(0,11)

In [58]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [59]:
arr[8]

8

In [60]:
arr[1:5]

array([1, 2, 3, 4])

In [61]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [62]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [63]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [64]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [65]:
arr[0:5] = 100 # burada 0. indeksten baslayarak besinci indekse kadar olan degerleri 100 e esitlemis olduk  

In [66]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [67]:
arr = np.arange(0,11)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
slice_of_arr = arr[0:6] # burada arr dizininin bir kopyasini alarak slice_of_arr degisken adinda yeni bir dizin olusturuyoruz. 

In [70]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [71]:
slice_of_arr[:] = 99 # slice_of_arr dizininin tum indekslerini 99 a esitlemis oldum

In [72]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [73]:
arr # arr dizinin kopyasini olusturp uzerinde calismis olduk orjinalinde bir degisiklik olmadi 

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [74]:
arr_copy = arr.copy()

In [75]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [76]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [77]:
arr_copy[:] = 100

In [78]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [79]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [80]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [81]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [82]:
arr_2d[0][0] # ilk satir ilk sutundaki eleamni bulur

5

In [83]:
arr_2d[1][2]

30

In [84]:
arr_2d[1,2] # birinci dizindeki satir uzerinde ikinci dizindeki stunda olani getirir arr_2d[1][2] ile aynidir.

30

In [85]:
arr_2d[0:2,1:] # o. dizinden 2. dizine kadar olan satirlari 2 dahil degil aliyor bunun uzerinden 1. dizinden itibaren sonuna kadar sutunlari aliyor

array([[10, 15],
       [25, 30]])

In [86]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [87]:
arr = np.arange(1,11)

In [88]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr > 5 # boolen degerler uretir

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [90]:
bool_arr = arr>5

In [91]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [92]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [93]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [94]:
arr[arr<3]

array([1, 2])

In [95]:
arr_2d = np.arange(50).reshape(5,10)

In [96]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [97]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

{NumPy Operations }

In [98]:
import numpy as np

In [99]:
arr = np.arange(0,11)

In [100]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [102]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [103]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [104]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [105]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [106]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [107]:
1 / 0

ZeroDivisionError: division by zero

In [ ]:
arr / arr

In [ ]:
0/0

In [ ]:
1/arr

In [ ]:
arr ** 2

In [ ]:
np.sqrt(arr) # sayilarin karekokunu alir

In [ ]:
np.exp(arr) # ustel ifadeleri

In [ ]:
np.max(arr)

In [ ]:
arr.max()

In [ ]:
np.min(arr)

In [ ]:
min(arr)

In [ ]:
np.sin(arr)

In [ ]:
np.log(arr)

In [ ]:
import numpy as np
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-np.max(arr_2)

In [ ]:
import numpy as np
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d[2,1]

In [ ]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,50]))
arr_2d[:1,1:]

In [ ]:
arr = np.arange(1,6)
arr[arr>3]

In [ ]:
arr

In [ ]:
arr_1 = np.arange(0,10)
arr_2 = arr_1 * 3
np.max(arr_2)

In [ ]:
arr_1 = np.array([4,9,16,25,36])
arr_2 = np.array([2,3,4,5,6])
np.sqrt(arr_1)-arr_2

In [ ]:
arr=np.arange(1,37)

In [ ]:
arr

In [ ]:
arr.shape

In [ ]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

In [ ]:
a*b

In [ ]:
ab = []
for i in range(0, len(a)):
    ab.append(a[i]*b[i])

In [ ]:
a1 = np.array(a)
b1 = np.array(b)

In [ ]:
a1*b1

In [ ]:
my_matrix = [[1,2,3], [4,5,6],[7,8,9]]

In [ ]:
type(my_matrix)

In [ ]:
np.arange(0,10)

In [ ]:
np.arange(0,11,2)

In [ ]:
np.arange(0,31,3)

In [ ]:
np.zeros(3)

In [ ]:
np.zeros(10)

In [ ]:
np.zeros(10, dtype=int)

In [ ]:
np.zeros((5,5))

In [ ]:
np.zeros((5,5),dtype=str) # unicode string

In [ ]:
np.zeros((5,5),dtype=int)

In [ ]:
np.zeros((5,5),dtype=bool)

In [ ]:
np.zeros((4,4),dtype=str)

# **"ones"**

In [ ]:
np.ones(3)

In [ ]:
np.ones((3,3))

In [ ]:
np.ones((3,5), dtype=int)

In [ ]:
np.ones((4,4), dtype=str)

In [ ]:
np.ones((4,4), dtype=bool)

## Full

In [ ]:
np.full((3,5),3)

In [ ]:
np.full((3,5),"3")

In [ ]:
np.full((3,5),"Clarusway")

# linspace

In [ ]:
np.linspace(0,10,3)

In [ ]:
np.linspace(0,10,3)

In [ ]:
np.linspace(0,10,50)

In [ ]:
np.linspace(0,10) # default 50 degeri var

In [ ]:
np.linspace(0,10,51)

In [ ]:
np.linspace(0,10,51, dtype="int")

In [ ]:
set(np.linspace(0,10,51, dtype="int"))

## eye

In [ ]:
np.eye(4)

## Random

In [ ]:
np.random.rand(3)

In [ ]:
np.random.rand(2) # 0 ile 1 arasinda 2 sayi uretiyor rastgele

In [ ]:
np.random.rand(5,5) # uniform dagilimli bir matris getiriyor

In [ ]:
np.random.rand(5)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(np.random.rand(5000000), bins = 75) # uniform dagilimi gormek icin rand icindeki degeri artirarak gozlem yapabiliriz
plt.show()

# randn

In [ ]:
np.random.randn(2)

In [ ]:
np.random.randn(5,5)

In [ ]:
plt.hist(np.random.randn(555), bins =55)
plt.show()

In [ ]:
plt.hist(np.random.randn(5555), bins =55)
plt.show()

In [ ]:
plt.hist(np.random.randn(55555), bins =55)
plt.show()

In [ ]:
np.random.randn(55555).mean()

In [ ]:
np.random.randn(55555).std()

In [ ]:
np.random.randn(55555).std()**2

# randint