___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

<h1><p style="text-align: center;">NumPy Lesson, Session - 2 (Part-2) </p><h1>

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [3]:
arr[8]

8

In [4]:
arr[-1]

10

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [ ]:
# arr[start:stop:step]

In [7]:
arr[1::2]

array([1, 3, 5, 7, 9])

In [8]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [ ]:
arr

In [ ]:
arr[0:5] = 100

arr

In [ ]:
a = [0, 2, 4, 6, 8]

In [ ]:
a[0:3] = 100

In [ ]:
arr = np.arange(0,11)

In [ ]:
arr

In [ ]:
slice_of_arr = arr[0:6]

In [ ]:
slice_of_arr

In [ ]:
slice_of_arr[:] = 99

In [ ]:
slice_of_arr

Now note the changes also occur in our original array!

In [ ]:
arr

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
arr_copy = arr.copy()

arr_copy

In [ ]:
arr_copy[0:6] = [0,1,2,3,4,5]

In [ ]:
arr_copy

In [ ]:
arr

## Indexing a 2D array (matrices)

<p>The general format is <b>arr_2d[row][col]</b> or <b>arr_2d[row,col]</b>. I recommend usually using the comma notation for clarity.</p>

In [ ]:
arr_2d = np.array([[5,10,15], [20,25,30], [35, 40,45]])

arr_2d

In [ ]:
arr_2d[1]

In [ ]:
arr_2d[1][0]

In [ ]:
arr_2d[1, 0]

In [ ]:
arr_2d[2]

In [ ]:
arr_2d[2, :]

In [ ]:
arr_2d

In [ ]:
arr_2d[:,1]

In [ ]:
arr_2d[:,2]

In [ ]:
arr_2d[1,1] = 55

In [ ]:
arr_2d

In [ ]:
arr_2d.dtype

In [ ]:
arr_2d[0,0] = 3.3

In [ ]:
arr_2d

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
v = np.arange(0, 30, 3)

In [ ]:
v

In [ ]:
v[1]

In [ ]:
v[5]

In [ ]:
idx_list = [1,3,5]

In [ ]:
v[idx_list]

In [ ]:
v[[1,3,5]]

Fancy indexing allows the following

In [ ]:
arr2d = np.zeros((10,10), dtype = int)

In [ ]:
arr2d

In [ ]:
arr2d.shape

In [ ]:
arr_length = arr2d.shape[1]

In [ ]:
arr_length

In [ ]:
arr2d[0]

In [ ]:
arr2d[3]

In [ ]:
for i in range(arr_length):
    arr2d[i] = i
    
    
arr2d

In [ ]:
arr2d[[2,4,6,8]]

In [ ]:
arr2d[[6,4,2,7]]

<h3>any_array[[row indices], [column indices]]</h3>

In [ ]:
jj = np.arange(1,17).reshape((4,4))
jj

In [ ]:
jj[[1,2], [0,3]]

In [ ]:
jj[[0,2,3], [0,1,3]]

### Using ***basic index*** and ***fancy index*** together

In [ ]:
jj

In [ ]:
jj[1, [1,3]]

In [ ]:
jj[[0, 3], 1]

### Using ***basic slicing*** and ***fancy index*** together

In [ ]:
jj

In [ ]:
jj[0:, [1,2]]

In [ ]:
jj[1:3, [1,2]]

In [ ]:
jj[1:3, 1:3]

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to find useful images.

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)

In [ ]:
arr

In [ ]:
arr > 4

In [ ]:
bool_arr = arr > 4

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr > 4]

In [ ]:
arr[(arr != 3) & (arr != 4)]

-``& ==> and``

-``| ==> or``

# NumPy Operations

## Arithmetic Operations

#### You can easily perform array with array arithmetic, or scalar with array arithmetic.

In [ ]:
arr = np.arange(0,10)
arr

In [ ]:
arr + arr

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
arr / arr

In [ ]:
1 / arr

In [ ]:
arr ** 2

In [ ]:
v = np.array([1,2,3,4,5])

In [ ]:
v

In [ ]:
v - 1

In [ ]:
v * 5

In [ ]:
v * 5 / 10 - 1

## Universal Array Functions

#### Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [ ]:
arr

In [ ]:
np.log10(10000)

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
np.sin(arr)

In [ ]:
np.sin(np.pi/2)

In [ ]:
np.tan(np.pi/4)

## Statistical Calculations

* ``np.mean(arr,axis=0)`` | Returns mean along specific axis

* ``arr.sum()`` | Returns sum of arr

* ``arr.min()`` | Returns minimum value of arr

* ``arr.max(axis=0)`` | Returns maximum value of specific axis

* ``np.var(arr)`` | Returns the variance of array

* ``np.std(arr,axis=1)`` | Returns the standard deviation of specific axis

* ``arr.corrcoef()`` | Returns correlation coefficient of array

## A sample solve in Linear Algebra using NumPy

In [ ]:
# x = 2, y = 3

# The End of the Session - 2

___


<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" alt="Rossum"></p>

___

## You can take a look at an attractive [official tutorial](https://numpy.org/devdocs/user/absolute_beginners.html) for beginners of NumPy.