NameError: name 'population' is not defined

NameError: name 'df' is not defined

In [88]:
import numpy as np

# randint

In [89]:
np.random.randint(1,100)

27

In [90]:
np.random.randint(1,100,10)

array([17, 45, 80, 27, 11, 28, 61, 37,  1, 29])

In [91]:
np.random.randint(1,100, size=10)

array([82, 25, 34, 53,  6, 42, 30, 51, 89, 45])

In [92]:
np.random.randint(5, size=10)

array([0, 2, 0, 3, 0, 3, 0, 0, 0, 4])

In [93]:
np.random.randint(5, size=(2,4)) # iki satir 4 sutun

array([[4, 0, 0, 0],
       [2, 3, 4, 3]])

In [94]:
np.random.randint(5,25, size=(2,4)) # 5 ile 25 arasinda 25 dahil degil iki boyutlu : iki satir 4 sutun

array([[16,  5, 16, 23],
       [19,  9, 15, 24]])

In [95]:
np.random.randint(1,[3,50,100]) # alt siniri 1 olan ust siniri 3, 50 ve 100 olan uc stunlu tek boyutlu 

array([ 2, 24, 65])

In [96]:
np.random.randint(1,[3,50,100], size=(5,3)) # # alt siniri 1 olan ust siniri 3, 50 ve 100 olan 5 satirli 3 stunlu matris . matrisin 3. stunu maximum 99 yer alabilir

array([[ 2,  9, 42],
       [ 2, 20, 60],
       [ 2, 10, 77],
       [ 1, 32, 34],
       [ 2,  7, 83]])

In [97]:
np.random.randint([1,30,70], 110)

array([ 83, 108, 101])

# Array Atribus

In [98]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [99]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [100]:
ranarr

array([31, 18, 19,  8,  2,  9, 48,  8, 23, 39])

# Reshape

In [101]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [102]:
ranarr.reshape(2,5)

array([[31, 18, 19,  8,  2],
       [ 9, 48,  8, 23, 39]])

# max, min, argmax, argmin

In [103]:
ranarr

array([31, 18, 19,  8,  2,  9, 48,  8, 23, 39])

In [104]:
ranarr.max()

48

In [105]:
ranarr.argmax()

6

In [106]:
ranarr.min()

2

In [107]:
ranarr.argmin()

4

# Some other attributes

# ndim : number of array dimensions

# shape : tuple of array dimensions

In [108]:
arr.shape

(25,)

In [109]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [110]:
arr.reshape(1,25).shape # shape ine bakiyoruz bir satir 25 sutunlu

(1, 25)

In [111]:
arr.reshape(25,1) # 25 satirlik 1 stunluk 

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [112]:
arr.reshape(25,1).shape

(25, 1)

# size : number of elements in the array

# dtype: data types of the array

In [113]:
arr.dtype

dtype('int32')

In [114]:
a = np.random.randint(10, size =10)

In [115]:
a

array([5, 7, 1, 2, 0, 2, 7, 8, 7, 0])

In [116]:
a.dtype

dtype('int32')

In [117]:
b = np.full((4,6),2.2)

In [118]:
b

array([[2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2]])

In [119]:
b.dtype

dtype('float64')

In [120]:
c=np.full((4,6), 2.2)

In [121]:
c

array([[2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2]])

In [122]:
c.dtype

dtype('float64')

# ndim : number of array dimensions

In [123]:
b.ndim

2

# size : number of elements in the array

In [124]:
a

array([5, 7, 1, 2, 0, 2, 7, 8, 7, 0])

In [125]:
a.size

10

In [126]:
b

array([[2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2],
       [2.2, 2.2, 2.2, 2.2, 2.2, 2.2]])

In [127]:
b.size

24

# Concatenation of the Arrays

In [128]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [129]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [130]:
z = np.array([7,8,9])

In [131]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2d matrix

In [132]:
a1 = np.concatenate([x,y]).reshape(2,3)

In [133]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [134]:
np.concatenate([a1,a1]) # axis = o olmasi demek x ekseni 0 yani satirlar sifir oldugu icin satirlamara ekleme yapar

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [135]:
np.concatenate([a1,a1], axis = 1) # axis = 1 yaptigimizda sutunlara ekleme yapar

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Splitting of the Arrays

In [136]:
x = np.array([1,2,3,99,99,3,2,1])

In [137]:
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [138]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [139]:
a,b,c = np.split(x,[3,5]) # ary [:3] ; ary [3:5] ; ary [5:] axis = 0 oldugu icin tek boyutlu satiri esas aliyor

In [140]:
a

array([1, 2, 3])

In [141]:
b

array([99, 99])

In [142]:
c

array([3, 2, 1])

In [143]:
np.split(x,4) # dort esit arraye boluyor. buradaki 4 un eleman sayisini tam boluyor olmasi lazim aksi taktirde hata verir

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

In [144]:
np.split(x,5) # buradaki 4 un eleman sayisini tam boluyor olmasi lazim aksi taktirde hata verir

ValueError: array split does not result in an equal division

# 2d matrix

In [145]:
m = np.arange(20).reshape(5,4)

In [146]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [147]:
np.split(m,[2,4])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [148]:
np.split(m,[1,3], axis=1) # stunlara gore boldu

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [149]:
np.vsplit(m,[1,3]) # vertikle dikey exende boluyoruz

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [150]:
np.vsplit(m,[2,4]) 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [151]:
upper, lower = np.vsplit(m,[3])

In [152]:
upper # dikey olarak boluyor

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [153]:
lower

array([[12, 13, 14, 15],
       [16, 17, 18, 19]])

In [154]:
np.vsplit(m,5) # iki boyutlu 5 array e boluyor

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]])]

In [155]:
np.vsplit(m,2) # vertikil 5 satiri ikiye bolemeyeceginden hata verir

ValueError: array split does not result in an equal division

In [156]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [157]:
np.hsplit(m,[2]) # horizantel olarak boluyor 0 ile 1 ve 2 ile 3 cu indexler bolunuyor

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19]])]

In [158]:
left, right = np.hsplit(m,[2])

In [159]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [160]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

In [161]:
aaa, bbb = np.hsplit(m,[2])

In [162]:
aaa

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17]])

In [163]:
bbb

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19]])

# Sorting of the Arrays

In [164]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [165]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [166]:
v.sort() # changed implace bunu kullaninca yerinde degistirir

In [167]:
v

array([1, 2, 3, 4, 5])

# 2d matrix

In [168]:
twoD = np.random.randint(5,100,(3,3))
twoD

array([[34, 18, 14],
       [48, 21, 58],
       [50, 71, 54]])

In [169]:
np.sort(twoD, axis=0) # her bir stun kendi arasinda siralandi 

array([[34, 18, 14],
       [48, 21, 54],
       [50, 71, 58]])

In [170]:
np.sort(twoD, axis=1)

array([[14, 18, 34],
       [21, 48, 58],
       [50, 54, 71]])

# the End of the NumPy Session-1

# Numpy Indexing and Selection

In [171]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [172]:
arr[8]

8

In [173]:
arr[-1]

10

In [174]:
arr[1:5]

array([1, 2, 3, 4])

In [175]:
arr[0:5] # arr[start:stop:step]

array([0, 1, 2, 3, 4])

In [176]:
arr[1::2] # arr[start:stop:step]

array([1, 3, 5, 7, 9])

In [177]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

# Broadcasting

In [ ]:
arr

In [ ]:
arr[0:5] = 100 # 0 ile 5 arasina 100 verebiliyoruz
arr

In [ ]:
a = [0, 2, 4, 6, ]

In [60]:
arr = np.arange(0,11)

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
slice_of_arr = arr[0:6]

In [63]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [64]:
slice_of_arr[:] = 99 # bastan sona tum elemanlarina 99 atiyorum
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [65]:
arr # ilk alti elemanina 99 atandigi goruluyor

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [66]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [67]:
arr_copy[0:6] = [0,1,2,3,4,5]

In [68]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexing a 2d array (matrices)

In [69]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [70]:
arr_2d[1] # satirdaki birinci index

array([20, 25, 30])

In [71]:
arr_2d[1][0]

20

In [72]:
arr_2d[1,0]

20

In [73]:
arr_2d[0:2, 1:]

array([[10, 15],
       [25, 30]])

In [74]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [75]:
arr_2d[:2, :]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [76]:
arr_2d[2, :]

array([35, 40, 45])

In [77]:
arr_2d[:, 1]

array([10, 25, 40])

In [78]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [79]:
arr_2d[:, 2]

array([15, 30, 45])

In [80]:
arr_2d[1, 1]

25

In [81]:
arr_2d[1, 1] = 55

In [82]:
arr_2d # 55 olarak degistirdik

array([[ 5, 10, 15],
       [20, 55, 30],
       [35, 40, 45]])

In [83]:
arr_2d.dtype

dtype('int32')

In [84]:
dtype()

NameError: name 'dtype' is not defined

# Fancy Indexing

In [ ]:
v = np.arange(0,30,3)
v

In [ ]:
v[1]

In [ ]:
v[5]

In [ ]:
idx_list = [1,3,5]

In [ ]:
v[idx_list]

In [ ]:
v[[1,3,5]]

In [ ]:
arr2d = np.zeros((10,10), dtype=int)
arr2d

In [ ]:
arr2d.shape

In [ ]:
arr_length = arr2d.shape[1] # satir uzunlugu

In [ ]:
arr_length

In [ ]:
arr2d[0]

In [ ]:
arr2d[3]

In [ ]:
for i in range(arr_length):
    arr2d[i] = i

arr_2d[]

In [ ]:
arr2d[[2,4,6,8]]

In [ ]:
arr2d[[6,4,2,7]]

In [ ]:
any_array[[row indices], [column indices]]

In [ ]:
jj = np.arange(1,17).reshape((4,4))
jj

In [ ]:
jj[[1,2],[0,3]]

In [ ]:
jj[[0,2,3],[0,1,3]]

# Using basic index and fancy index together

In [ ]:
jj

In [ ]:
jj[1, [1,3]] # birinci satirdaki 1 ve 3 stunu verir

In [ ]:
jj[[0,3],1]

In [ ]:
Using basic 

In [ ]:
jj

In [ ]:
jj[0:,[1,2]]

In [ ]:
jj[1:3,[1,2]] # fancy sliylama

In [ ]:
jj[1:3,1:3] # normal slijslama

# Selection

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
arr>4

In [ ]:
bool_arr = arr >4

In [ ]:
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr>4]

""" - & ==> and 
- | ==> or """

In [ ]:
arr[(arr !=3) & (arr !=4)]

# Arithmetic Operations

In [ ]:
arr = np.arange(0,10)
arr

In [ ]:
arr + arr

In [ ]:
arr * arr

In [ ]:
arr - arr

In [ ]:
arr / arr

In [ ]:
1/arr

In [ ]:
arr ** 2

In [ ]:
v = np.array([1,2,3,4,5])

In [ ]:
v - 1

In [ ]:
v*5


In [ ]:
v*5 /10-1

# Universal Array Functions

In [ ]:
np.log10(10000)

In [ ]:
np.sqrt(arr)

In [ ]:
np.exp(arr)

In [ ]:
np.sin(arr)

In [ ]:
np.sin(np.pi/2)

In [ ]:
np.tan(np.pi/4)