# NumPy Lab, Session


# A sample Solve in Linear Algebra using NumPy

In [4]:
import numpy as np

In [5]:
# 3*x+y = 9
# x+y = 8

In [53]:
a = np.array([[3,1],[1,2]])
b = np.array([9,8])

In [54]:
a

array([[3, 1],
       [1, 2]])

In [55]:
b

array([9, 8])

# from numpy import * bu sekilde baska bir yontem

# Using array-generating functions

# arange

In [9]:
x = np.arange(0,10,1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
y = np.arange(-1,1,0.2)
y

array([-1.00000000e+00, -8.00000000e-01, -6.00000000e-01, -4.00000000e-01,
       -2.00000000e-01, -2.22044605e-16,  2.00000000e-01,  4.00000000e-01,
        6.00000000e-01,  8.00000000e-01])

In [11]:
# linspace and longspace

In [12]:
np.linspace(0,10,25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [13]:
np.logspace(0,10,10, base=10)

array([1.00000000e+00, 1.29154967e+01, 1.66810054e+02, 2.15443469e+03,
       2.78255940e+04, 3.59381366e+05, 4.64158883e+06, 5.99484250e+07,
       7.74263683e+08, 1.00000000e+10])

In [14]:
np.random.seed(0)
np.random.rand(5,5)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443]])

### random data

In [15]:
np.random.seed(0)
np.random.rand(5,5)

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606],
       [0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443]])

In [16]:
np.random.rand(5,5)

array([[0.63992102, 0.14335329, 0.94466892, 0.52184832, 0.41466194],
       [0.26455561, 0.77423369, 0.45615033, 0.56843395, 0.0187898 ],
       [0.6176355 , 0.61209572, 0.616934  , 0.94374808, 0.6818203 ],
       [0.3595079 , 0.43703195, 0.6976312 , 0.06022547, 0.66676672],
       [0.67063787, 0.21038256, 0.1289263 , 0.31542835, 0.36371077]])

In [17]:
np.random.randn(3,3)

array([[-1.70627019,  1.9507754 , -0.50965218],
       [-0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656]])

In [18]:
# a diagonal matrix
np.diag([1,2,3,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [20]:
np.diag([1,2,3,4], k=1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

## Manipulating arrays

In [21]:
B = np.array([i for i in range(5)])
B

array([0, 1, 2, 3, 4])

In [22]:
B = np.array(range(5))
B

array([0, 1, 2, 3, 4])

In [24]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [25]:
row_mask = np.array([0,0,0,1,1], dtype = bool)
B[row_mask]

array([3, 4])

In [26]:
x = np.arange(0,10,0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [28]:
mask = (5<x) & (x<7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [29]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [30]:
indices = np.where(mask)
indices

(array([11, 12, 13, 14], dtype=int64),)

In [31]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [32]:
x[indices]

array([5.5, 6. , 6.5, 7. ])

### diag 

In [36]:
A = np.array([[1,2,3,4],[5,6,7,8],[1,2,3,4],[5,6,7,8]])
A

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
np.diag(A)

array([1, 6, 3, 8])

In [38]:
np.diag([1, 6, 3, 8])

array([[1, 0, 0, 0],
       [0, 6, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 8]])

In [41]:
np.diag(A, k=-3)

array([5])

In [42]:
np.diag(A, k=-1)

array([5, 2, 7])

In [ ]:
#take

In [44]:
v2 = np.arange(-3,3)
v2

array([-3, -2, -1,  0,  1,  2])

In [45]:
# fancy indexing
row_index = [1,3,5]
v2[row_index]

array([-2,  0,  2])

In [46]:
v2.take(row_index)

array([-2,  0,  2])

In [ ]:
## choose

In [48]:
which = [1,0,1,0]
choices = [[-2,-3,-4,-5],[6,7,8,9]]

In [49]:
np.choose(which, choices)

array([ 6, -3,  8, -5])

In [50]:
which = [1,0,1,2]
choices = [[-2,-3,-4,-5],[6,7,8,9],[1,2,3,4]]

In [51]:
np.choose(which, choices)

array([ 6, -3,  8,  4])